"""
py2app build configuration for Piclo Bot.
Creates a self-contained macOS .app bundle.

Usage:
    python3 setup.py py2app

Output:
    dist/Piclo Bot.app
"""

from setuptools import setup

APP = ['menubar.py']
DATA_FILES = [
    # bot.py and config.py are included as data files so menubar can find them at runtime
    ('', ['bot.py', 'config.py']),
]

OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'icon.icns',  # Generated by build_app.sh from robot_icon_preview.png
    'plist': {
        'CFBundleName': 'Piclo Bot',
        'CFBundleDisplayName': 'Piclo Bot',
        'CFBundleIdentifier': 'com.piclobot.app',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'LSMinimumSystemVersion': '12.0',
        'LSUIElement': True,  # Menu bar app — no Dock icon
        'NSHighResolutionCapable': True,
        'NSDocumentsFolderUsageDescription': 'Piclo Bot needs access to your projects folder.',
        'NSDesktopFolderUsageDescription': 'Piclo Bot can save files to your Desktop.',
        'NSMicrophoneUsageDescription': 'Piclo Bot uses the microphone for voice transcription.',
    },
    'packages': [
        'anthropic',
        'telegram',
        'httpx',
        'httpcore',
        'anyio',
        'certifi',
        'h11',
        'idna',
        'sniffio',
        'distro',
        'jiter',
        'pydantic',
        'pydantic_core',
        'annotated_types',
        'typing_extensions',
    ],
    'includes': [
        'rumps',
        'config',
        'pywhispercpp',
        'pywhispercpp.model',
    ],
    'excludes': [
        'tkinter',
        'unittest',
        'pydoc',
    ],
    'site_packages': True,
    'strip': True,
    'semi_standalone': False,
}

setup(
    name='Piclo Bot',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
